- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/AbstractFunctional.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/CreateUserProfileFuncTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/EndpointSecurityTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/RetrieveUserProfileFuncTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/WelcomeTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/client/FuncTestRequestHandler.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/domain/entities/UserProfile.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/infrastructure/controllers/UserProfileController.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/util/UserProfileValidator.java
https://tools.hmcts.net/jira/browse/RDCC-252
RDCC 252 : Added functional test cases for POST and GET endpoints. Currently the functional test cases are ignored state since it requires live Idam service connectivity but it is not available now. So functional test cases are tested with local mock service to pass. Once Idam service is UP then Ignored test cases needs to be activated.
```
[ ] Yes
[x] No
```
> RDCC 252 : Added functional test cases for POST and GET endpoints

- infrastructure/main.tf
- src/main/resources/bootstrap.yaml
Fix for Master Build Pipeline
```
[ ] Yes
[ X] No
```
> Fix for Master build

- infrastructure/main.tf
It is read the postgres user and database details
```
[ ] Yes
[ X] No
```
> Fixing vault keys to read DB username

- build.gradle
User profile build pipeline fix
```
[ ] Yes
[ X] No
```
> JENKINS-MASTER-FIX: build pipe line issue fixed

- Jenkinsfile_nightly
- Jenkinsfile_parameterized
- charts/rd-user-profile-api/values.yaml
- database/init-db.sh
- docker-compose.yml
- infrastructure/ithc.tfvars
- infrastructure/main.tf
- infrastructure/output.tf
- src/integrationTest/resources/application.yml
- src/main/resources/application.yaml
AAT build - Jenkins fix for Database credentials to be picked up by the application
```
[ ] Yes
[X ] No
```
> Jenkins build for AAT

- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/EndpointSecurityTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/WelcomeTest.java
> RDCC-345 reverting functional test runner back to ignore

- src/main/java/uk/gov/hmcts/reform/userprofileapi/domain/IdamRegistrationInfo.java
- src/main/resources/db/migration/V1_1__init_tables.sql
- src/test/java/uk/gov/hmcts/reform/userprofileapi/domain/IdamRegistrationInfoTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/domain/entities/UserProfileTest.java
> Rdcc 352 Test and refactoring and database schema consolidation

- build.gradle
- src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/UserProfileController.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/controller/UserProfileControllerTest.java
> Rdcc 352 3

- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/CreateNewUserProfileWithDuplicateUserIntTest.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/client/CreateUserProfileData.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/client/GetUserProfileResponse.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/client/IdamUserResponse.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/config/IdamStatusConfiguration.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/domain/IdamRolesInfo.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/IdamServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/IdamStatus.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/UserProfileCreator.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/util/IdamStatusResolver.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/util/JsonFeignResponseHelper.java
- src/main/resources/db/migration/V1_1__init_tables.sql
- src/test/java/uk/gov/hmcts/reform/userprofileapi/client/IdamRegisterUserRequestTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/client/IdamUserResponseTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/domain/service/IdamRolesInfoTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/domain/service/UserProfileCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/util/IdamStatusResolverTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/util/UserProfileValidatorTest.java
https://tools.hmcts.net/jira/browse/RDCC-391
RDCC-391 resolve Idam Status in User Profile API.
```
[ ] Yes
[x] No
```
> RDCC-391 resolve Idam Status

- src/main/resources/db/migration/V1_1__init_tables.sql
- src/main/resources/db/migration/V1_2__modify_check_constraint.sql
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/RDCC-391
RDCC-391 resolve Idam Status in User Profile API.
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[x] No
> RDCC-391 New DB migration script added

- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/RetrieveMultipleUserProfilesIntTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/RetrieveUserProfileIntTest.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/client/GetUserProfileWithRolesResponse.java
N/A
amended idamStatus and idamMessage to correspond with PRD, updaed related tests
```
[ ] Yes
[X] No
```
> RDCC-345 amended idamStatus and idamMessage to correspond with PRD

- src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/UserProfileController.java
- src/main/resources/application.yaml
Adding new auth service for XUI and updated swagger docs.
```
[ ] Yes
[x] No
```
> Adding auth service and updated swagger

- src/main/java/uk/gov/hmcts/reform/userprofileapi/client/GetUserProfileWithRolesResponse.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/UserProfileRetriever.java
> RDCC-275 Preview idam message

- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/UpdateUserProfileIntTest.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/client/UpdateUserProfileData.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/UserProfileUpdator.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/util/UserProfileValidator.java
https://tools.hmcts.net/jira/browse/RDCC-430
https://tools.hmcts.net/jira/browse/RDCC-431
```
[ ] Yes
[x ] No
```
> Fixed bug for 430/431 Case Sensivity & Email

- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/client/IdamClient.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/config/TestConfigProperties.java
- src/functionalTest/resources/application-functional.yaml
RDCC-428 Functional test cases fixed with latest credentials
```
[ ] Yes
[x] No
```
> RDCC-428 Functional test cases fixed with latest credentials

- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/UserProfileCreator.java
Roles updation issue fixed
Roles updation issue fixed
```
[ ] Yes
[x] No
```
> Roles updation issue fixed

- Jenkinsfile_CNP
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/AbstractFunctional.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/CreateUserProfileFuncTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/EndpointSecurityTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/RetrieveMultipleUserProfileFuncTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/RetrieveUserProfileFuncTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/UpdateUserProfileFuncTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/WelcomeTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/client/FuncTestRequestHandler.java
- src/functionalTest/resources/application-functional.yaml
- src/main/resources/application.yaml
code merge to demo branch to fix functional test cases.
```
[ ] Yes
[ ] No
```
> Code-merge-functional-yaml-file

- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/CreateUserProfileFuncTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/RetrieveUserProfileFuncTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/UpdateUserProfileFuncTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/client/IdamClient.java
to make jenkins build green committing the changes. 
```
[ ] Yes
[X ] No
```
> code committed to fix functional test case

- Jenkinsfile_CNP
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/client/IdamClient.java
- src/functionalTest/resources/application-functional.yaml
- src/main/resources/application.yaml
pointing functional test cases to aat
```
[ ] Yes
[ X] No
```
> pointing functional test cases to aat

- src/main/resources/db/migration/V1_3__add_index_for_idam_id.sql
> Adding V1_3 script for unique indexing on Idam ID

- Jenkinsfile_CNP
merge the code to master
```
[ ] Yes
[X ] No
```
> enable build

- Jenkinsfile_CNP
code enabling for build pipeline
```
[ ] Yes
[ X] No
```
> removed step to move the code next level

- src/smokeTest/java/uk/gov/hmcts/reform/userprofileapi/SmokeTest.java
Added log statement
```
[ ] Yes
[ X] No
```
> Logging within Smoke test

- src/smokeTest/java/uk/gov/hmcts/reform/userprofileapi/SmokeTest.java
Smoke test changes
```
[ ] Yes
[ X] No
```
> Trying to get the prod build go green

- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/RetrieveUserProfileIntTest.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/util/UserProfileValidator.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/util/UserProfileValidatorTest.java
RDCC-485
RDCC-485
```
[ ] Yes
[x] No
```
> RDCC-485 removed UUID validation

- Jenkinsfile_CNP
- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-447
Enforcing Junit coverage to be above the given threshold via Gradle-Jenkins build.
```
[ ] Yes
[X] No
```
> RDCC-447 added Jacoco unit test coverage check on build

- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/RetrieveMultipleUserProfileFuncTest.java
JIRA link (if applicable)
RDCC-460
functional test case fix
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[x] No
> RDCC-460 functional test case fix

- Jenkinsfile_CNP
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/CreateNewUserProfileIntTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/UpdateUserProfileIntTest.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/client/CreateUserProfileData.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/util/UserProfileValidator.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/client/CreateUserProfileDataTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/util/UserProfileValidatorTest.java
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/RDCC-497
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[x] No
> RDCC-497 Email validation issue

- Jenkinsfile_CNP
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RDCC-561
adding FR team service name in authorised service list in userprofile.
```
[ ] Yes
[ X] No
```
> RDCC-561: Code changes to add fr team service name in authorized list

- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/AbstractFunctional.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/CreateUserProfileFuncTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/EndpointSecurityTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/UpdateUserProfileFuncTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/WelcomeTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/client/IdamClient.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/CreateNewUserProfileWithDuplicateUserIntTest.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/UserProfileController.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/domain/feign/IdamFeignClient.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/IdamService.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/IdamServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/UserProfileCreator.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/util/JsonFeignResponseHelper.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/assertions/UserProfileResourceAssert.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/client/GetUserProfileRequestTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/client/IdamServiceTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/client/UserProfileResourceTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/controller/UserProfileControllerTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/data/UserProfileTestDataBuilder.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/domain/service/UserProfileCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/repository/UserProfileQueryProviderTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/util/JsonFeignResponseHelperTest.java
https://tools.hmcts.net/jira/browse/RDCC-528
RDCC-528 Replace PUT with POST call for duplicate user profile
```
[ ] Yes
[x] No
```
> RDCC-528 Replace PUT with POST call for duplicate user profile

- src/main/java/uk/gov/hmcts/reform/userprofileapi/client/UserProfileRolesResponse.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/UserProfileUpdator.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/client/UserProfileRolesResponseTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/domain/service/UserProfileUpdatorTest.java
https://tools.hmcts.net/jira/browse/RDCC-454
Add and delete roles for user
```
[ ] Yes
[x ] No
```
> RDCC-454:addroles and delete roles attributes changed

- Dockerfile
- Jenkinsfile_CNP
- build.gradle
- charts/rd-user-profile-api/Chart.yaml
- charts/rd-user-profile-api/requirements.yaml
- charts/rd-user-profile-api/values.aat.template.yaml
- charts/rd-user-profile-api/values.preview.template.yaml
- charts/rd-user-profile-api/values.sandbox.template.yaml
- charts/rd-user-profile-api/values.yaml
- src/functionalTest/resources/application-functional.yaml
- src/main/resources/bootstrap.yaml
- web.config
> RDCC-478 AKS changes based on workshop

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/RDCC-478
```
[ ] Yes
[ ] No
```
> RDCC-478 - disable AAT deploy

- charts/rd-user-profile-api/Chart.yaml
- charts/rd-user-profile-api/values.yaml
https://tools.hmcts.net/jira/browse/RDCC-478
```
[ ] Yes
[ ] No
```
> Ingress patch

- src/main/resources/bootstrap.yaml
> Fix appinsights

- src/main/java/uk/gov/hmcts/reform/userprofileapi/constant/UserProfileConstant.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/UserProfileCreator.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/UserProfileRetriever.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/UserProfileUpdator.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/util/IdamStatusResolver.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/util/UserProfileValidator.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/client/UserProfileConstantTest.java
https://tools.hmcts.net/jira/browse/RDCC-542
Please see here for the list of issues (this list will change once this PR is merged):
https://sonarcloud.io/project/issues?id=RDUSERPROFILEAPI&resolved=false
fixing critical and major sonar issues
```
[ ] Yes
[x] No (I hope not)
```
> RDCC-542 fixing sonar issues

- build.gradle
> bump reform health starter

- src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/response/UserProfileWithRolesResponse.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/domain/entities/UpdatedUserDetails.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/domain/enums/ExceptionType.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/exception/UndefinedException.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/AuditService.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/ExceptionService.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/ValidationHelperService.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/ValidationService.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/AuditServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/ExceptionServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileRetriever.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileUpdator.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/ValidationHelperServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/ValidationServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/util/UserProfileValidator.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/domain/entities/UpdatedUserDetailsTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/ExceptionServiceImplTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileRetrieverTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileServiceTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileUpdatorTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/ValidationHelperServiceTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/ValidationServiceImplTest.java
https://tools.hmcts.net/jira/browse/RDCC-418
```
[ ] Yes
[ ] No
```
> Rdcc 418 634 ac1

- Jenkinsfile_nightly
- Jenkinsfile_parameterized
> RDCC-606_1 Adding fix for the nightly build

- src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/response/UserProfileRolesResponse.java
RDCC-418
Changed response 
```
[ ] Yes
[X] No
```
> Rdcc 418 v3 Update status response field change

- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/ExceptionServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/ValidationHelperServiceImpl.java
RDCC-418
added more loggers for testing
```
[ ] Yes
[X] No
```
> RDCC-418 added more loggers for testing

- Jenkinsfile_CNP
- src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/advice/UserProfileControllerAdvice.java
RDCC-418
Added more loggers to see stacks trace of exception
```
[ ] Yes
[X] No
```
> Rdcc 418 v3 Added more loggers to see stacks trace of exception

- config/owasp/suppressions.xml
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/CreateNewUserProfileWithDuplicateUserIntTest.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/response/UserProfileResponse.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileCreator.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/ValidationHelperServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/util/IdamStatusResolver.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/controller/response/UserProfileResponseTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/util/IdamStatusResolverTest.java
> Fixing failing Demo build - Sonar Issues

- build.gradle
- charts/rd-user-profile-api/Chart.yaml
- charts/rd-user-profile-api/values.preview.template.yaml
- charts/rd-user-profile-api/values.yaml
- config/owasp/suppressions.xml
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RDCC-635
refactor: updated idam env values in charts and updated token(RDCC-635) 
No
> refactor: updated idam env values in charts and updated token(RDCC-635) 

- charts/rd-user-profile-api/Chart.yaml
- charts/rd-user-profile-api/values.preview.template.yaml
- charts/rd-user-profile-api/values.yaml
- config/owasp/suppressions.xml
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RDCC-635
refactor: updated microservice chart to support sidam demo(RDCC-635)
No
> refactor: updated microservice chart to support sidam demo(RDCC-635)

- charts/rd-user-profile-api/Chart.yaml
- charts/rd-user-profile-api/values.yaml
https://tools.hmcts.net/jira/browse/RDCC-635
refactor: updated microservice with Idam url
No
> refactor: updated microservice with Idam url

- build.gradle
- charts/rd-user-profile-api/Chart.yaml
- security.sh
https://tools.hmcts.net/jira/browse/RDCC-682
> fix for security and helm chart

- audit.json
https://tools.hmcts.net/jira/browse/RDCC-682
> RDCC-682 false positives fix

- build.gradle
NA
Bump org.flywaydb.flyway from 5.0.7 to 6.1.0
No
> Bump org.flywaydb.flyway from 5.0.7 to 6.1.0

- src/main/resources/application.yaml
RDCC-727:
service names added in the list 
```
[ ] Yes
[X ] No
```
> RDCC-727: changing app version

- src/main/resources/application.yaml
RDCC-751
adding ia and fpl service names in the authorisation list
```
[ ] Yes
[X ] No
```
> adding ia and fpl service name

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/RDCC-755
fix:pref test set up
No
> fix:pref test set up

- build.gradle
Fix sonar changes suggested by DevOps
```
[ ] Yes
[X] No
```
> Prod sonar fix suggested by devops

- build.gradle
- config/owasp/suppressions.xml
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/AbstractFunctional.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/AddRolesWithIdamIntTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/CreateNewUserProfileIntTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/CreateNewUserProfileWithDuplicateUserIntTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/CreateNewUserProfileWithIdamErrorsIntTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/RetrieveUserProfileInternalServerErrorIntTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/UpdateUserProfileIntTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/controller/UserProfileControllerTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/controller/response/UserProfileCreationResponseTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/controller/response/UserProfileDataResponseTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/controller/response/UserProfileResponseTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/controller/response/UserProfileWithRolesResponseTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/domain/entities/AuditTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/domain/entities/UserProfileTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/helper/CreateUserProfileTestDataBuilder.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/helper/UserProfileTestDataBuilder.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/repository/AuditRepositoryTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/repository/UserProfileRepositoryTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/resource/UserProfileCreationDataTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileQueryProviderTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileServiceTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileUpdatorTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/ValidationHelperServiceTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/ValidationServiceImplTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/util/UserProfileMapperTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/util/UserProfileValidatorTest.java
https://tools.hmcts.net/jira/browse/RDCC-872
Addressing review comments
```
[ ] Yes
[✔︎] No
```
> RDCC-872 addressing review comments, removed mocks and added verify(s)

- build.gradle
- charts/rd-user-profile-api/Chart.yaml
- config/owasp/suppressions.xml
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/UpdateUserProfileFuncTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/UpdateUserProfileIntTest.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/advice/UserProfileConstants.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/advice/UserProfileControllerAdvice.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/resource/UpdateUserProfileData.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/controller/advice/UserProfileConstantsTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/resource/UpdateUserProfileDataTest.java
https://tools.hmcts.net/jira/browse/RDCC-824
Validation for entering First and Last Name on PUT Endpoint
```
[ ] Yes
[✘] No
```
> RDCC-824: Validation for entering First and Last Name on PUT Endpoint

- Jenkinsfile_CNP
- Jenkinsfile_parameterized
- charts/rd-user-profile-api/values.preview.template.yaml
- config/owasp/suppressions.xml
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/docs/SwaggerPublisher.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/AddRolesWithIdamIntTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/CreateNewUserProfileIntTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/CreateNewUserProfileWithDuplicateUserIntTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/CreateNewUserProfileWithIdamErrorsIntTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/RetrieveMultipleUserProfilesIntTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/RetrieveUserProfileIntTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/RetrieveUserProfileInternalServerErrorIntTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/RetrieveUserProfileWithIdamErrorsIntTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/UpdateUserProfileIntTest.java
Moving changes from https://github.com/hmcts/rd-user-profile-api/pull/279 into Demo
> RDCC-863: moving changes from Master to Demo

- config/owasp/suppressions.xml
re  deploying demo requires CVE to be updated
```
[ ] Yes
[X] No
```
> RDCC-1221 : re  deploying demo

- src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/UserProfileController.java
https://tools.hmcts.net/jira/browse/RDCC-969
**THIS IS THE PR FOR CHANGES TO MASTER**
The changes were approved and tested in this PR: https://github.com/hmcts/rd-user-profile-api/pull/302
- The Request and Response payloads for all APIs should be populated
- The description of all APIs should be consistent with their meaning
- All possible error codes and error descriptions are present
```
[ ] Yes
[x] No
```
> RDCC-969, MASTER: Update Swagger Descriptions for APIs

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/request/UserProfileDataRequest.java
RDCC-1033
Remove json property
```
[ ] Yes
[X ] No
```
> feat: Remove json property

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/ValidationHelperServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/ValidationHelperServiceTest.java
https://tools.hmcts.net/jira/browse/RDCC-930
Bringing changes from Master PR: https://build-beta.platform.hmcts.net/job/HMCTS_RD/job/rd-user-profile-api/job/PR-333/ to this (Demo) PR.
```
[ ] Yes
[✘] No
```
> RDCC-930, Demo: Re-write Exception Tests

- Jenkinsfile_CNP
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-1440
removing installCharts() from Jenkinsfile(s)
```
[ ] Yes
[x] No
```
> RDCC-1440, Master: removing installCharts() from Jenkinsfile_CNP

- src/main/resources/bootstrap.yaml
https://github.com/hmcts/rd-user-profile-api/pull/382
```
[ ] Yes
[X] No
```
> Add app insights instrumentation key

- charts/rd-user-profile-api/Chart.yaml
Demo chart upgrade since flux has v10
```
[ ] Yes
[ ] No
```
> Upgrading chart version since flux has 0.0.10

- config/owasp/suppressions.xml
- src/main/resources/application.yaml
RDCC-1661
RDCC-1661
```
[ ] Yes
[ ] No
```
> RDCC-1661 adding aac service

- config/owasp/suppressions.xml
RDCC-1693
RDCC-1693 adding suppression for CVE since master build is failing
```
[ ] Yes
[ ] No
```
> RDCC-1693 adding suppression for CVE

- config/owasp/suppressions.xml
- src/integrationTest/resources/application.yml
- src/main/java/uk/gov/hmcts/reform/userprofileapi/config/FeignInterceptorConfiguration.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/WelcomeController.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/advice/UserProfileControllerAdvice.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/repository/IdamRepository.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/ExceptionServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/IdamServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileCreator.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/util/JsonFeignResponseHelper.java
- src/main/resources/application.yaml
**JIRA link (if applicable)**
https://tools.hmcts.net/jira/browse/RDCC-1583
**Change description**
Adding component name to all application logs
```
[ ] Yes
[x] No
```
> RDCC-1583: Adding component name to all application logs

- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileRetriever.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileRetrieverTest.java
https://tools.hmcts.net/jira/browse/RDCC-1694
```
[ ] Yes
[ ] No
```
> RDCC-1582: removing logger

- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/client/FuncTestRequestHandler.java
- src/functionalTest/resources/application-functional.yaml
- src/integrationTest/resources/application.yml
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RDCC-1775
feat:  masked secret key
```
[ ] Yes
[ X] No
```
> feat:  masked secret key

- audit.json
- build.gradle
- charts/rd-user-profile-api/Chart.yaml
- charts/rd-user-profile-api/values.yaml
N/A
UP Security Scan Fix
```
[ ] Yes
[x] No
```
> UP Nightly Build Fix & Add env specific vars in values.yaml file

- infrastructure/state.tf
feat:remove unused variables from terraform script
```
[ ] Yes
[ X] No
```
> feat:remove unused variables from terraform script

- charts/rd-user-profile-api/values.preview.template.yaml
- src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/UserProfileController.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/request/processor/TelemetryRequestProcessor.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/controller/request/processor/TelemetryRequestProcessorTest.java
RDCC-1820
Masking the email IDs in UP API URL
```
[ ] Yes
[X ] No
```
> feat : Masking the email in API URL(RDCC-1820)

- build.gradle
- infrastructure/state.tf
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/AddRolesToExistingUserFuncTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/CreateUserProfileFuncTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/DeleteRolesToExistingUserFuncTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/DeleteUserProfileFuncTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/EndpointSecurityTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/ReInviteUserFuncTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/RetrieveMultipleUserProfileFuncTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/RetrieveUserProfileFuncTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/UpdateUserProfileFuncTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/WelcomeTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/docs/SwaggerPublisher.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/AddRolesWithIdamIntTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/AuthorizationEnabledIntegrationTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/CreateNewUserProfileIntTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/CreateNewUserProfileWithDuplicateUserIntTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/CreateNewUserProfileWithIdamErrorsIntTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/DeleteUserProfileIntTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/ReInviteUserProfileIntTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/RetrieveMultipleUserProfilesIntTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/RetrieveUserProfileIntTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/RetrieveUserProfileInternalServerErrorIntTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/RetrieveUserProfileWithIdamErrorsIntTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/UpdateUserProfileIntTest.java
- src/smokeTest/java/uk/gov/hmcts/reform/userprofileapi/SmokeTest.java
fix serenity report to filter integration , functional, Smoke Tests
```
[ ] Yes
[X] No
```
> fix serenity report to filter integration , functional, Smoke Tests

- README.md
- build.gradle
- src/contractTest/java/uk/gov/hmcts/reform/userprofileapi/IdamConsumerTest.java
feat:updated README.md file and pact related changes
```
[ ] Yes
[X] No
```
> feat:updated README.md file and pact related changes

- build.gradle
RDCC-1851
feat:nightly build fix
```
[ ] Yes
[X ] No
```
> feat:nightly build fix

- build.gradle
RDCC-1851
feat:sonarqube issues fix
```
[ ] Yes
[ X] No
```
> feat:sonarqube issues fix

- src/contractTest/java/uk/gov/hmcts/reform/userprofileapi/IdamConsumerTest.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/domain/feign/IdamFeignClient.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/IdamService.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/IdamServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/IdamServiceImplTest.java
RDCC-1562
removing user registration api from pact verification
```
[ ] Yes
[X] No
```
> Pact test changes

- build.gradle
(RDCC-1876)
This PR covers the library bump ups in UP
```
[ ] Yes
[X ] No
```
> Bump : Bump ups library versions(RDCC-1876)

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/AbstractFunctional.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/AddRolesToExistingUserFuncTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/DeleteRolesToExistingUserFuncTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/config/DbConfig.java
- src/functionalTest/resources/application-functional.yaml
- src/functionalTest/resources/delete-functional-test-data.sql
RDCC-1739
Feat: RDCC-1739 : Create Delete script for deleting functional test case data
```
[ ] Yes
[X] No
```
> Feat: RDCC-1739 : Create Delete script for deleting functional test case data

- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/AbstractFunctional.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/config/DbConfig.java
RDCC-1739
feat: RDCC-1739 Delete script for test case data deletion.
```
[ ] Yes
[X] No
```
> feat: RDCC-1739 Delete script for test case data deletion.

- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/AbstractFunctional.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/config/DbConfig.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/util/DataBaseUtil.java
RDCC-1739
feat: RDCC-1739 Delete script for deleting functional test case data.
```
[ ] Yes
[X] No
```
> feat: RDCC-1739 Delete script for deleting functional test case data.

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-1433
feat:disabling the threads from the build gradlew file
```
[ ] Yes
[X ] No
```
> disabling the threads from the build gradlew file

- charts/rd-user-profile-api/values.preview.template.yaml
- config/owasp/suppressions.xml
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/client/FuncTestRequestHandler.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileCreator.java
feat: adding condition to ignore get and post calls  when roles matches
```
[ ] Yes
[X] No
```
> feat: adding condition to ignore get and post calls  when roles matches

- charts/rd-user-profile-api/Chart.yaml
- charts/rd-user-profile-api/requirements.yaml
- charts/rd-user-profile-api/values.yaml
https://tools.hmcts.net/jira/browse/RDCC-2021
```
[ ] Yes
[X] No
```
> Chart updates master

- charts/rd-user-profile-api/Chart.yaml
- charts/rd-user-profile-api/requirements.yaml
- charts/rd-user-profile-api/values.yaml
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RDCC-2021
Bringing changes from Master
```
[ ] Yes
[x] No
```
> RDCC-2021, PerfTest: Bringing changes from Master

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/RDCC-2073
```
[ ] Yes
[X] No
```
> Added method call to sync branches

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-2107
Addressed CVE 2020-17521 by upgrading apache groovy
```
[ ] Yes
[x] No
```
> build: Addressed CVE 2020-17521 by upgrading groovy

- build.gradle
RDCC-2017
This PR deals with the Bump up Jar versions from Bot
```
[ ] Yes
[ X] No
```
> Bump : RDCC-2017 -Upgrade Jar versions

- charts/rd-user-profile-api/Chart.yaml
- charts/rd-user-profile-api/values.preview.template.yaml
- charts/rd-user-profile-api/values.yaml
- src/main/resources/application.yaml
- src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/RDCC-2141
```
[ ] Yes
[X] No
```
> Update s2s secret reference

- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/client/IdamOpenIdClient.java
[RDCC-2332](https://tools.hmcts.net/jira/browse/RDCC-2332)
_Adding retry to createUser() in IdamOpenIdClient_
```
[ ] Yes
[x] No
```
> RDCC-2332: Adding Retry to createUser() in IdamOpenIdClient

- audit.json
- charts/rd-user-profile-api/Chart.yaml
- charts/rd-user-profile-api/requirements.yaml
JIRA link
https://tools.hmcts.net/jira/browse/RDCC-2462
Security scan reported issue fix
```
[ ] Yes
[x] No
```
> fix: Security scan reported issue fix

- audit.json
- build.gradle
RDCC-2507
This change upgrade jar version and restore the earlier version of dius.pact for serenity report
```
[ ] Yes
[ X] No
```
> DependBot : Upgrade Jar versions(RDCC-2507)

- charts/rd-user-profile-api/Chart.yaml
- charts/rd-user-profile-api/values.preview.template.yaml
- charts/rd-user-profile-api/values.yaml
- src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/RDCC-2505
```
[ ] Yes
[X] No
```
> Update app insights key secret name

- src/main/resources/application.yaml
fix:RDCC-2632 added hikari configuration
fix:RDCC-2632 added hikari configuration
```
[ ] Yes
[X] No
```
> fix:RDCC-2632 added hikari configuration

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-2743
RDCC-2743 : Fixing the CVE-2021-29425
```
[ ] Yes
[x] No
```
> RDCC-2743 : Fixing the CVE-2021-29425

- charts/rd-user-profile-api/Chart.yaml
https://tools.hmcts.net/jira/browse/RDCC-2746
Helm chart Version updated
```
[ ] Yes
[ X] No
```
> fix:RDCC-2746-Helm chart version updated

- Jenkinsfile_nightly
- audit.json
JIRA link
https://tools.hmcts.net/jira/browse/RDCC-2777
Fixed security scan reported issue
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[x] No
> fix: RDCC-2777 Fixed failing FT in nightly by adding LD key and fixed security scan reported issue

- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/AbstractFunctional.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/UserProfileFunctionalTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/client/FuncTestRequestHandler.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/client/IdamOpenIdClient.java
https://tools.hmcts.net/jira/browse/RDCC-2865
updating functional test to avoid failure from 504
```
[ ] Yes
[x] No
```
> RDCC-2865: Functional Test Fix (504 scenarios)

- build.gradle
> upgraded spring boot version from 2.4.5 to 2.4.6 to fix cvv

- security.sh
> changed the order of command in security.sh to fix security scan

- build.gradle
RDCC-3141
RDCC-3141 fix CVE-2021-33037
```
[ ] Yes
[X] No
```
> RDCC-3141 : fix CVE-2021-33037

- build.gradle
RDCC-3150
This change is to remove the Bintray reference
```
[ ] Yes
[ X] No
```
> fix : remove bintray reference(RDCC-3150)

- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/UserProfileFunctionalTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/client/FuncTestRequestHandler.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/RetrieveUserProfileIntTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/RetrieveUserProfileInternalServerErrorIntTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/RetrieveUserProfileWithIdamErrorsIntTest.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/UserProfileController.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/util/UserProfileUtil.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/controller/UserProfileControllerTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/util/UserProfileUtilTest.java
https://tools.hmcts.net/jira/browse/RDCC-2820
Deprecation of Email as a Query Param in APIs
```
[ ] Yes
[x] No
```
> RDCC-2820: Deprecation of Email as a Query Param in APIs

- charts/rd-user-profile-api/Chart.yaml
https://tools.hmcts.net/jira/browse/RDCC-3169
RDCC-3169 - Update chart versions in all PRD repos
```
[ ] Yes
[X] No
```
> RDCC-3169 - Update chart versions in all PRD repos

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-3237
Fix CVE issues CVE-2021-22119
```
[ ] Yes
[X] No
```
> RDCC-3237 - Fix CVE issues CVE-2021-22119

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-3254
Suppressed CVE-2020-23171
```
[ ] Yes
[X] No
```
> RDCC-3254 - Suppressed CVE-2020-23171

- security.sh
https://tools.hmcts.net/jira/browse/RDCC-3239
Fix Security scan issue
```
[ ] Yes
[X] No
```
> RDCC-3239- Fix Security scan issue

- audit.json
- infrastructure/terraform.tf
https://tools.hmcts.net/jira/browse/RDCC-3284
Nightly build failure and use fixed version for azuread
```
[ ] Yes
[x] No
```
> fix: Nightly build failure and use fixed version for azuread

- audit.json
Nightly Build Fix: Adding entries to audit.json
```
[ ] Yes
[x] No
```
> Nightly Build Fix: Adding entries to audit.json

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- bin/run-in-docker.sh
- charts/rd-user-profile-api/Chart.yaml
- charts/rd-user-profile-api/values.preview.template.yaml
- charts/rd-user-profile-api/values.yaml
- docker-compose.yml
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/util/CustomSerenityRunner.java
- src/functionalTest/resources/application-functional.yaml
- src/integrationTest/resources/application.yml
- src/main/java/uk/gov/hmcts/reform/userprofileapi/config/ServiceTokenGeneratorConfiguration.java
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RDCC-3277
Review and remove hard code values 
```
[ ] Yes
[x] No
```
> RDCC-3277: Removed hard coded string in the configuration files.

- charts/rd-user-profile-api/values.yaml
- config/owasp/suppressions.xml
- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDCC-3507
Create postgress v11 DB.
```
[ ] Yes
[X] No
```
> RDCC-3507: Create a v11 Postgres DB - Demo

- infrastructure/main.tf
Added postgresql_version
```
[ ] Yes
[x] No
```
> Added postgresql_version

- infrastructure/main.tf
Updating DB Secrets
```
[ ] Yes
[x] No
```
> Updating DB Secrets

- infrastructure/main.tf
Updating DB Secrets
```
[ ] Yes
[x] No
```
> UP PerfTest: Updating DB Secrets

- charts/rd-user-profile-api/Chart.yaml
- charts/rd-user-profile-api/values.aat.template.yaml
- charts/rd-user-profile-api/values.yaml
- infrastructure/main.tf
https://tools.hmcts.net/confluence/display/RSTR/CHG5006041+-+PRD+and+AM+Postgress+Databases+Upgrade+to+v11+Release+Implementation+Plan
```
[ ] Yes
[X] No
```
> Update configurations to point to v1 DB

- Jenkinsfile_CNP
- Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/RDCC-3640
Publishing Test Reports in Jenkins
```
[ ] Yes
[X] No
```
> Publish Reports in Jenkins

- infrastructure/main.tf
https://tools.hmcts.net/confluence/pages/viewpage.action?pageId=1525468401
Delete v9.6 DB. Post DB migration activity
```
[ ] Yes
[X] No
```
> Remove v9.6 DB and temporary v11 secret

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-3782
Collating Dependabot PRs
```
[ ] Yes
[x] No
```
> RDCC-3782: Collating dependabot PRs

- Jenkinsfile_nightly
- build.gradle
- config/owasp/suppressions.xml
> CVE-2018-1258 CVE fix

- src/test/java/uk/gov/hmcts/reform/userprofileapi/controller/request/UserProfileDataRequestTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/controller/response/UserProfileDataResponseTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/repository/AuditRepositoryTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/resource/UpdateUserProfileDataTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileRetrieverTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileUpdatorTest.java
[RDCC-3462](https://tools.hmcts.net/jira/browse/RDCC-3462)
Address remaining Sonar issues in Ref Data repos
```
[ ] Yes
[ x] No
```
> fixed sonar minor issues

- Jenkinsfile_nightly
- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-4048
CVE Fixes
```
[ ] Yes
[x] No
```
> RDCC-4048: CVE Fixes

- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/UserProfileFunctionalTest.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/config/RestAuthenticationEntryPoint.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/config/SecurityConfiguration.java
https://tools.hmcts.net/jira/browse/RDCC-3449
https://tools.hmcts.net/jira/browse/RDCC-3449
```
[ ] Yes
[x] No
```
> idam bearer token logging

- src/contractTest/java/uk/gov/hmcts/reform/userprofileapi/UserProfileProviderTest.java
- src/contractTest/java/uk/gov/hmcts/reform/userprofileapi/UserProfileProviderTestConfiguration.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/AbstractFunctional.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/UserProfileFunctionalTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/client/IdamOpenIdClient.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/UserProfileController.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/ResourceCreator.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/ResourceUpdator.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileCreator.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileService.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileUpdator.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/controller/UserProfileControllerTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileServiceTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileUpdatorTest.java
https://tools.hmcts.net/jira/browse/RDCC-3951
- Update both attributes and roles
```
[ ] Yes
[x] No
```
> feat: RDCC-3951 Update both attributes and roles

- audit.json
https://tools.hmcts.net/jira/browse/RDCC-3951
fix: Nightly build failure
```
[ ] Yes
[x] No
```
> fix: Nightly build failure

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-4088
Fixing CWE - adding dependency: `name: 'spring-security-core', version: '5.6.1'`
```
[ ] Yes
[x] No
```
> RDCC-4088: Fixing CWE

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- src/functionalTest/resources/application-functional.yaml
https://tools.hmcts.net/jira/browse/RDCC-833
fix: Removed hard coded secret
```
[ ] Yes
[x] No
```
> fix: Removed hard coded secret

- charts/rd-user-profile-api/Chart.yaml
https://tools.hmcts.net/jira/browse/RDCC-4139
Updated java chart version to 3.7.3
```
[ ] Yes
[x] No
```
> fix: Updated java chart version to 3.7.3

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-4299
Collating DependaBot PRs
```
[ ] Yes
[x] No
```
> RDCC-4299: Collating DependaBot PRs

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-4331
```
[ ] Yes
[X] No
```
> RDCC-4331 updated for cve 2020-36518

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-4380
```
[ ] Yes
[X ] No
```
> RDCC-4380 CVE Fix

- Dockerfile
- build.gradle
- docker-compose.yml
https://tools.hmcts.net/jira/browse/RDCC-4350
Java 17 Migration
```
[ ] Yes
[x] No
```
> RDCC-4350: Java 17 Migration

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-4395
Upgrading PITest Versions
```
[ ] Yes
[x] No
```
> RDCC-4395: CVE & Mutation Fixes

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-4427
```
[ ] Yes
[X] No
```
> Nightly build issues

- src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/advice/UserProfileControllerAdvice.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/controller/advice/UserProfileControllerAdviceTest.java
https://tools.hmcts.net/jira/browse/RDCC-4254
UP - Handle Verbose Error Messages
```
[ ] Yes
[X] No
```
> UP - Handle Verbose Error Messages

- build.gradle
CVE Fix for Spring Core
```
[ ] Yes
[ X] No
```
> cve fix for spring core

- src/main/java/uk/gov/hmcts/reform/userprofileapi/config/SecurityConfiguration.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/config/SecurityEndpointFilter.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/exception/UnauthorizedException.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/repository/IdamRepository.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/userprofileapi/exception/UnauthorizedExceptionTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/repository/IdamRepositoryTest.java
https://tools.hmcts.net/jira/browse/RDCC-4680
To handle 500 HTTP responses
```
[ ] Yes
[ x] No
```
> Feat:To handle 500 HTTP responses

- renovate.json
https://tools.hmcts.net/jira/browse/RDCC-4820
Configured renovate
```
[ ] Yes
[x] No
```
> config: RDCC-4820 Configured renovate

- .github/workflows/combine-prs.yml
https://tools.hmcts.net/jira/browse/RDCC-4857
```
[ ] Yes
[X] No
```
> RDCC-4857:UP API Automerge Renovate PR's

- charts/rd-user-profile-api/Chart.yaml
- config/owasp/suppressions.xml
CVE Fix for Tomcat Embed Core
```
[ ] Yes
[X] No
```
> cve fix for tomcat embed

- charts/rd-user-profile-api/Chart.yaml
- charts/rd-user-profile-api/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDCC-5048
Upgrade java chart 
```
[ ] Yes
[x] No
```
> RDCC-5048 Upgrade java chart 

- config/owasp/suppressions.xml
> Address CVE-2020-23171 for all refdata REPOs

- Jenkinsfile_CNP
> Hack to push through the images  and chart on master

- Dockerfile
> Use latest agent

- build.gradle
> Upgrade feign client

- src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/UserProfileController.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/IdamServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileRetriever.java
Add logging in debug mode
```
[ ] Yes
[X] No
```
> loggers debug mode

- charts/rd-user-profile-api/Chart.yaml
- charts/rd-user-profile-api/values.yaml
- src/main/resources/application.yaml
Adding logging level to enable debugging in AAT
```
[ ] Yes
[X] No
```
> Adding logging level

- build.gradle
> Upgrade Launch Darkly client

- charts/rd-user-profile-api/Chart.yaml
- charts/rd-user-profile-api/values.aat.template.yaml
- src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/UserProfileController.java
Also enabling debugging in staging.
```
[ ] Yes
[x] No
```
> Added more logging in controller

- Jenkinsfile_CNP
Add env vars
```
[ ] Yes
[x] No
```
> Add missing env vars

- src/main/resources/application.yaml
Enable Tomcat access logs debug
```
[ ] Yes
[X] No
```
> Enable Tomcat access logs

- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/IdamServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileRetriever.java
Loggers to identify Idam Call
```
[ ] Yes
[X] No
```
> Loggers to identify idam call

- build.gradle
- config/owasp/suppressions.xml
> Upgrade IDAM Java client

- src/main/resources/application.yaml
Default is 10 seconds.
```
[ ] Yes
[x] No
```
> Increase IDAM client timeout

- src/main/resources/db/migration/V1_7__drop_index_for_idam_id.sql
Remove Duplicate Index on Idam_id
```
[ ] Yes
[X] No
```
> Drop duplicate index on Idam_id

- src/main/java/uk/gov/hmcts/reform/userprofileapi/resource/UserProfileCreationData.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/exception/UnauthorizedExceptionTest.java
https://tools.hmcts.net/jira/browse/RDCC-5593
RDCC-5593 user-profile code smell fix
```
[ ] Yes
[x ] No
```
> RDCC-5593 user-profile code smell fix

- charts/rd-user-profile-api/Chart.yaml
- infrastructure/terraform.tf
https://tools.hmcts.net/jira/browse/RDCC-5894
```
[ ] Yes
[X] No
```
> Upgrade Terraform and helm :: RDCC-5894

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- charts/rd-user-profile-api/Chart.yaml
https://tools.hmcts.net/jira/browse/RDCC-5931
```
[ ] Yes
[X] No
```
> Replace after with afterSuccess for depreciated : RDCC-5931

- audit.json
https://tools.hmcts.net/jira/browse/RDCC-6410
adding entries to `audit.json`
```
[ ] Yes
[x] No
```
> RDCC-6410: adding entries to `audit.json`

- charts/rd-user-profile-api/Chart.yaml
https://tools.hmcts.net/jira/browse/RDCC-6374
Upgrading chart version to `4.0.13`
```
[ ] Yes
[x] No
```
> RDCC-6374: Upgrading chart version to latest

- .github/renovate.json
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-6421
Added update renovate.json
```
[ ] Yes
[x] No
```
> RDCC-6421 Add renovate.json

- Dockerfile
- build.gradle
- charts/rd-user-profile-api/Chart.yaml
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/docs/SwaggerPublisherTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/AuthorizationEnabledIntegrationTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/SpringBootIntegrationTest.java
- src/integrationTest/resources/application-test.yml
- src/main/java/uk/gov/hmcts/reform/userprofileapi/config/SecurityConfiguration.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/config/SwaggerConfiguration.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/UserProfileController.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/WelcomeController.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/oidc/JwtGrantedAuthoritiesConverter.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/userprofileapi/oidc/JwtGrantedAuthoritiesConverterTest.java
https://tools.hmcts.net/jira/browse/RDCC-6338
```
[ ] Yes
[X] No
```
> Spring boot upgrade to 2.7.7 RDCC-6338

- audit.json
Security Scan issue
```
[ ] Yes
[X] No
```
> security scan issue

- src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/UserProfileController.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/WelcomeController.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/UserProfileQueryProvider.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/IdamServiceImpl.java
https://tools.hmcts.net/jira/browse/RDCC-6528
Addressing Sonar Issues
```
[ ] Yes
[x] No
```
> RDCC-6528: Addressing Sonar Issues

- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/IdamServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileCreator.java
- src/main/java/uk/gov/hmcts/reform/userprofileapi/util/FeatureConditionEvaluation.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/IdamServiceImplTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/util/FeatureConditionEvaluationTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/util/JsonFeignResponseUtilTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/util/UserProfileMapperTest.java
https://tools.hmcts.net/jira/browse/RDCC-6525
Adding unit tests to increase Mutation Coverage
```
[ ] Yes
[x] No
```
> RDCC-6525: Adding unit tests to increase Mutation Coverage

- audit.json
https://tools.hmcts.net/jira/browse/DTSRD-213
```
[ ] Yes
[X] No
```
> DTSRD-213 - add ignore to audit.json for 10096_Timestamp

- Jenkinsfile_CNP
- build.gradle
https://tools.hmcts.net/jira/browse/DTSRD-235
```
[ ] Yes
[x] No
```
> DTSRD-235 - update build.gradle for verifying pact and publish results

- src/main/java/uk/gov/hmcts/reform/userprofileapi/util/IdamStatusResolver.java
https://tools.hmcts.net/jira/browse/DTSRD-248
```
[ ] Yes
[X] No
```
> DTSRD-248 - update expired token error message

- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/AddAndDeleteRolesWithIdamIntTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/AuthorizationEnabledIntegrationTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/CreateNewUserProfileWithDuplicateUserIntTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/RetrieveMultipleUserProfilesIntTest.java
https://tools.hmcts.net/jira/browse/RDCC-6707
Wiremock Enhancement
```
[ ] Yes
[X] No
```
> UserProfileAPI:WireMock response enhancement

- Jenkinsfile_nightly
- deletescript/sql/delete-functional-data-script.sql
https://tools.hmcts.net/jira/browse/RDCC-6201
[RDCC-6201]- Delete functional Test data - User profile.
```
[ ] Yes
[ x] No
```
> [RDCC-6201]- Delete functional Test data - User profile.

- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/CreateNewUserProfileIntTest.java
https://tools.hmcts.net/jira/browse/RDCC-6742
```
[ ] Yes
[X] No
```
> Userprofile:Test cases can be clubbed as parameterised tests in all repositories

- src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileUpdator.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/userprofileapi/util/FeatureConditionEvaluationTest.java
https://tools.hmcts.net/jira/browse/RDCC-6819
[RDCC-6819]SonarQube Issue fix
```
[ ] Yes
[x ] No
```
> [RDCC-6819]SonarQube Issue fix

- build.gradle
https://tools.hmcts.net/jira/browse/DTSRD-660
Remedy for CVE-2023-2976
```
[ ] Yes
[x] No
```
> Update guava to 32.0.1-jre

- infrastructure/main.tf
- infrastructure/terraform.tf
- infrastructure/variables.tf
> DTSRD-1262.Upgrade Postgres to V15

- infrastructure/main.tf
- infrastructure/variables.tf
> DTSRD-1262 . Upgrade postgres

- Jenkinsfile_CNP
> DTSRD-1466.Remove branches to sync -userprofile demo and master

- Jenkinsfile_CNP
- infrastructure/main.tf
- infrastructure/terraform.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/DTSRD-1264
> DTSRD-1264.Upgrade to postgres V15 . - merge demo to perftest

- Jenkinsfile_CNP
- build.gradle
- charts/rd-user-profile-api/Chart.yaml
- infrastructure/main.tf
- infrastructure/terraform.tf
- infrastructure/variables.tf
> DTSRD-1263.merge V15 changes to ITHC and perftest branch

- src/main/resources/application.yaml
>  Update application.yaml .reverting connection string changes

- src/contractTest/java/uk/gov/hmcts/reform/userprofileapi/UserProfileProviderTest.java
https://tools.hmcts.net/jira/browse/RDCC-7097
[RDCC-7097]UP : Consumer Pact Test Cases needs to be added
- [ x] Does this PR introduce a breaking change
> [RDCC-7097]UP : Consumer Pact Test Cases needs to be added

- Jenkinsfile_CNP
- infrastructure/main.tf
- infrastructure/terraform.tf
- infrastructure/variables.tf
> DTSRD-1263.adding v15 scripts to master and sync to all branches

- Jenkinsfile_CNP
- infrastructure/main.tf
- infrastructure/terraform.tf
- infrastructure/variables.tf
> DTSRD-1893.Upgrading main branch to V16 and adding subnet_suffix 

- charts/rd-user-profile-api/Chart.yaml
- charts/rd-user-profile-api/values.yaml
> DTSRD-2442: PI33 Configure spot instances in non-production

- infrastructure/main.tf
> Update schema ownership

- infrastructure/terraform.tf
Update azurerm to 3.105.0 to fix build pipeline
> Update azurerm to 3.105.0

- build.gradle
> Update build.gradle . Fix Build

- Dockerfile
- acb.tpl.yaml
- build.gradle
https://tools.hmcts.net/jira/browse/DTSRD-3355
Java 21 upgrade
> DTSRD-3355

- .github/workflows/swagger.yml
- src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/docs/SwaggerPublisherTest.java
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/DTSRD-3562
Swagger Publishing
> DTSRD-3562 Swagger Publishing

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
https://tools.hmcts.net/jira/browse/DTSRD-3619
- remedy for CVE-2024-22233
- gradle 8.10.2
- spring-boot 3.3.4
- typo
- isolated fortifyScan config
> DTSRD-3619

- src/test/java/uk/gov/hmcts/reform/userprofileapi/util/UserProfileValidatorTest.java
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
> dummy space to trigger build

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/CME-253
- [ x] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
- [ x] Does this PR introduce a breaking change
> CME-253: Disable sync to ITHC for database monitoring testing

- infrastructure/main.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/CME-253
- [ x] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
- [ x] Does this PR introduce a breaking change
> CME-253: Database monitoring and alerting on RD repositories

- infrastructure/terraform.tf
https://tools.hmcts.net/jira/browse/CME-293
- [x ] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
- [ x] Does this PR introduce a breaking change
> CME-293: Update azurerm

- charts/rd-user-profile-api/Chart.yaml
- infrastructure/aat.tfvars
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/DTSRD-4453
Remove plpgsql from variables.tf
> DTSRD-4453
